apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "181b5ecf-e2e3-4216-bcea-932e86583049"
        - name: Vless_Path
          value: "/181b5ecf-e2e3-4216-bcea-932e86583049-vless"
        - name: Vmess_UUID
          value: "181b5ecf-e2e3-4216-bcea-932e86583049"
        - name: Vmess_Path
          value: "/181b5ecf-e2e3-4216-bcea-932e86583049-vmess"
        - name: Share_Path
          value: "/v2link"
